name: Doxygen Documentation

on:
  push:
    branches:
      - main  # You can specify other branches like 'develop' or 'feature/*'
  pull_request:
    branches:
      - main  # You can specify other branches if needed

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Doxygen
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz

      - name: Remove existing warning files
        run: |
          rm -f c-sample/doxygen_warnings.log
          rm -f cpp-sample/doxygen_warnings.log
          pwd
          ls c-sample/
          ls cpp-sample/

      - name: Run Doxygen for C samples
        run: |
          cd c-sample
          doxygen Doxyfile

      - name: Run Doxygen for C++ samples
        run: |
          cd cpp-sample
          doxygen Doxyfile

      - name: List files before copying logs
        run: |
          echo "Listing files in c-sample:"
          ls -l c-sample
          echo "Listing files in cpp-sample:"
          ls -l cpp-sample

      - name: Move Doxygen Warning Logs
        run: |
          mkdir -p log
          cp c-sample/doxygen_warnings.log log/
          cp cpp-sample/doxygen_warnings.log log/
      
      - name: Commit and Push Doxygen Logs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add log/
          git commit -m "Add updated Doxygen warning logs"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/S3CloudHubRepo/Doxygen-Sample.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload generated documentation (optional)
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-docs
          path: ./html  # or wherever your docs are generated
